# Generated by Django 4.2.3 on 2023-09-27 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat_automation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slab',
            name='gender',
        ),
        migrations.AddField(
            model_name='slab',
            name='select_one',
            field=models.CharField(blank=True, choices=[('General & Individual Firm', 'General & Individual Firm'), ('Woman and Senior Citizens (65+)', 'Woman and Senior Citizens (65+)'), ('Third Gender', 'Third Gender'), ('Physically challenged persons', 'Physically challenged persons'), ('War wounded gazetted freedom fighters', 'War wounded gazetted freedom fighters')], max_length=220, null=True),
        ),
    ]
