# Generated by Django 4.2.3 on 2023-09-27 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vat_automation_app', '0002_remove_slab_gender_slab_select_one'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=8801521, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
